apps/weblog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index' #creates an instance of the object welcome_controller
  get 'welcome/about'

resources :articles

  root 'welcome#index'

end

apps/weblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

apps/weblog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
	end
	def edit
	end
	def create
		render plain: params['article'].inspect
	end
end

apps/weblog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@name = "Charlotte"
  end

  def about
  end
end

apps/weblog/app/helpers/application_helper.rb
module ApplicationHelper
end

apps/weblog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

apps/weblog/app/views/articles/new.html.erb
<h1>New Article!</h1>

<%= form_for :article, url: articles_path do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %><br>
	<p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

apps/weblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

apps/weblog/app/views/welcome/about.html.erb
<h1>About Our Blog</h1>

<p>IT'S AWESOME!</p>

apps/weblog/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= @name %>